{
    'name': 'Aamalcom Hr Operations',
    'version': '1.0.0',
    'summary': 'Manage employee info change requests with approval and notifications',
    'category': 'Human Resources',
    'author': 'Lucidspire',
    'website': 'https://lucidspire.com',
    'depends': ['hr', 'mail','visa_process','internal_treasury'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/ir_sequence.xml',
        'data/mail_template.xml',
        'data/ir_cron.xml',
        'reports/probation_report.xml',
        'wizard/employee_selection_hr_views.xml',
        'wizard/hr_employee_reject_wizard_views.xml',
        'views/hr_medical_service_views.xml',
        'views/hr_employee_change_request_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_probation_extend_request_views.xml',
        'views/hr_exit_reentry_views.xml',
        'views/hr_annual_request_views.xml',
        'views/hr_business_views.xml',
        'views/hr_end_of_service_views.xml',
        'views/hr_onboarding_checklist_views.xml',
        'views/hr_onboarding_process_views.xml',
        'views/hr_resignation_views.xml',
        'views/hr_warning_views.xml',
        'views/hr_suspending_employee_views.xml',
        'views/hr_end_of_contract_views.xml',
        'views/menu.xml'
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}