{
    'name': 'Aamalcom Insurance',
    'version': '15.0.1.0.0',
    'category': 'Human Resources',
    'summary': 'Reimbursement, Deletion, Upgrade/Downgrade, Insurance Invoice and Reports',
    'depends': ['base', 'account', 'hr','visa_process','aamalcom_accounting'],
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/sequence.xml',
        'data/hdf_form_data.xml',
        'reports/report_action.xml',
        'reports/report_life_ins_inv_summary.xml',
        'reports/report_med_ins_inv_summary.xml',

        'views/account_move_views.xml',
        'views/hr_employee_views.xml',
        'views/medical_insurance_enrollment_views.xml',
        'views/swapping_border_to_iqama_views.xml',
        'views/insurance_reimbursement_view.xml',
        'views/medical_insurance_deletion_views.xml',
        'views/medical_insurance_class_change_views.xml',
        'views/medical_insurance_invoice_details_views.xml',
        'views/life_insurance_enrollment_views.xml',
        'views/life_insurance_deletion_views.xml',
        'views/life_insurance_class_change_views.xml',
        'views/life_insurance_invoice_details_views.xml',
        'views/hdf_form_views.xml',

        'wizard/life_insurance_invoice_wizard_views.xml',
        'wizard/medical_insurance_invoice_wizard_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
}
