from . import hr_employee_change_request
from . import hr_probation_extend_request
from . import hr_employee
from . import hr_medical_report
from . import hr_ere_request
from . import hr_annual_request
from . import hr_business_trip
from . import hr_resignation_document
from . import hr_end_of_service
from . import hr_onboarding_checklist
from . import hr_onboarding_process
from . import hr_resignation
from . import hr_suspending
from . import hr_warning
from . import hr_end_of_contract
from . import business_trip_from